import fs from 'node:fs/promises';
import path from 'node:path';
const root=path.resolve(process.cwd()),outFile=path.join(root,'data','latest.json');
const MARKET_DEFS=[['ganfeng','0.002460','赣锋锂业','002460.SZ','上游锂盐'],['tianqi','0.002466','天齐锂业','002466.SZ','上游锂矿'],['saltlake','0.000792','盐湖股份','000792.SZ','盐湖提锂'],['catl','0.300750','宁德时代','300750.SZ','下游电池'],['ganfeng_hk','116.01772','赣锋锂业H','01772.HK','上游锂盐'],['tianqi_hk','116.09696','天齐锂业H','09696.HK','上游锂矿'],['alb','106.ALB','Albemarle','ALB.NYSE','国际锂业'],['sqm','106.SQM','SQM','SQM.NYSE','国际锂业']].map(([key,secid,name,code,role])=>({key,secid,name,code,role}));
const MACRO_DEFS=[['dxy','100.UDI','美元指数'],['csi300','1.000300','沪深300'],['nasdaq','100.NDX','纳斯达克'],['oil','102.CL00Y','NYMEX原油']].map(([key,secid,name])=>({key,secid,name}));
const NEWS_FEEDS=[['zh','中文锂电新闻','https://news.google.com/rss/search?q=%E9%94%82%E7%9F%BF+OR+%E7%A2%B3%E9%85%B8%E9%94%82+OR+%E5%B9%BF%E6%9C%9F%E6%89%80&hl=zh-CN&gl=CN&ceid=CN:zh-Hans'],['en','Global lithium news','https://news.google.com/rss/search?q=%22lithium+carbonate%22+OR+%22lithium+price%22+OR+%22lithium+mining%22&hl=en-US&gl=US&ceid=US:en']];
const SOURCES=[{name:'东方财富行情接口',url:'https://quote.eastmoney.com/'},{name:'广州期货交易所（GFEX）',url:'https://www.gfex.com.cn/'},{name:'Trading Economics · Lithium',url:'https://tradingeconomics.com/commodity/lithium'},{name:'上海有色网 SMM',url:'https://www.smm.cn/'},{name:'Google News RSS',url:'https://news.google.com/'},{name:'rss2json',url:'https://rss2json.com/'}];
const clamp=(v,a=-1,b=1)=>Math.max(a,Math.min(b,v)),stripHtml=s=>String(s||'').replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim(),hash=s=>{let h=0;for(let i=0;i<s.length;i++)h=(h*31+s.charCodeAt(i))>>>0;return h},addMonths=(d,n)=>{const x=new Date(d);x.setMonth(x.getMonth()+n);return x};
function contractCandidates(){const out=[];for(let i=0;i<=6;i++){const d=addMonths(new Date(),i);out.push(`lc${String(d.getFullYear()).slice(2)}${String(d.getMonth()+1).padStart(2,'0')}`)}return[...new Set(out)]}
async function getJson(url,ms=25000){const ctl=new AbortController(),t=setTimeout(()=>ctl.abort(),ms);try{const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0','Accept':'application/json'},signal:ctl.signal,cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(t)}}
async function getText(url,ms=25000){const ctl=new AbortController(),t=setTimeout(()=>ctl.abort(),ms);try{const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0','Accept':'text/html,*/*'},signal:ctl.signal,cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.text()}finally{clearTimeout(t)}}
async function quote(def){const d=(await getJson(`https://push2.eastmoney.com/api/qt/stock/get?secid=${encodeURIComponent(def.secid)}&fields=f43,f57,f58,f59,f60,f169,f170,f47,f48`)).data,dec=Number(d?.f59??2);return{...def,name:d?.f58||def.name,code:d?.f57||def.code,price:Number(d?.f43)/10**dec,changePct:Number(d?.f170)/100,volume:Number(d?.f47||0),amount:Number(d?.f48||0)}}
async function kline(secid){const j=await getJson(`https://push2his.eastmoney.com/api/qt/stock/kline/get?secid=${encodeURIComponent(secid)}&fields1=f1,f2,f3,f4,f5,f6&fields2=f51,f52,f53,f54,f55,f56,f57,f58,f59,f60,f61&klt=101&fqt=1&beg=20240101&end=20500101&lmt=360`);return(j.data?.klines||[]).map(s=>{const a=s.split(',');return{d:a[0],o:+a[1],c:+a[2],h:+a[3],l:+a[4],v:+a[5],amount:+a[6],amp:+a[7],chg:+a[8],delta:+a[9]}})}
async function futures(){const quotes=(await Promise.allSettled(contractCandidates().map(code=>quote({secid:`225.${code}`,name:`碳酸锂${code.slice(2)}`,code})))).filter(x=>x.status==='fulfilled'&&x.value.price>0).map(x=>x.value);if(!quotes.length)throw new Error('No futures quote');quotes.sort((a,b)=>b.volume-a.volume);const main=quotes[0];return{...main,contract:main.code,klines:await kline(`225.${main.code}`),contracts:quotes.map(q=>({contract:q.code,name:q.name,price:q.price,changePct:q.changePct,volume:q.volume}))}}
async function market(def){const[q,k]=await Promise.all([quote(def),kline(def.secid)]);return{...q,secid:def.secid,role:def.role,klines:k}}
async function macro(def){const[q,k]=await Promise.all([quote(def),kline(def.secid)]);return{...q,secid:def.secid,klines:k}}
function parseSpotHtml(html){const desc=html.match(/<meta[^>]+name="description"[^>]+content="([^"]+)"/i)?.[1]?.replace(/&#39;/g,"'")||html.match(/<meta[^>]+content="([^"]+)"[^>]+name="description"/i)?.[1]?.replace(/&#39;/g,"'")||'',pm=desc.match(/to\s+([\d,]+)\s+CNY\/T\s+on\s+([^,]+),\s+(up|down)\s+([\d.]+)%/i),mm=desc.match(/past month,\s+Lithium(?:'s)? price has\s+(fallen|risen)\s+([\d.]+)%/i),ym=desc.match(/([\d.]+)%\s+(higher|lower)\s+than a year ago/i);if(!pm)throw new Error('Spot page schema changed');return{price:+pm[1].replace(/,/g,''),date:pm[2].trim(),dayPct:(pm[3].toLowerCase()==='down'?-1:1)*+pm[4],monthPct:mm?(mm[1].toLowerCase()==='fallen'?-1:1)*+mm[2]:null,yearPct:ym?(ym[2].toLowerCase()==='lower'?-1:1)*+ym[1]:null,unit:'CNY/T',sourceName:'Trading Economics',sourceUrl:'https://tradingeconomics.com/commodity/lithium'}}
function parseJinaSpot(md){const p=md.match(/Actual\s+([\d,]+)/i),d=md.match(/Daily Change\s+[^\n]*?(-?[\d.]+)%/i),m=md.match(/Monthly\s+(-?[\d.]+)%/i),y=md.match(/Yearly\s+(-?[\d.]+)%/i);if(!p)throw new Error('Jina spot schema changed');return{price:+p[1].replace(/,/g,''),date:new Date().toISOString().slice(0,10),dayPct:d?+d[1]:null,monthPct:m?+m[1]:null,yearPct:y?+y[1]:null,unit:'CNY/T',sourceName:'Trading Economics / Jina Reader',sourceUrl:'https://tradingeconomics.com/commodity/lithium'}}
async function spot(){const page='https://tradingeconomics.com/commodity/lithium';let last;for(let i=0;i<3;i++){try{return parseSpotHtml(await getText(page))}catch(e){last=e;await new Promise(r=>setTimeout(r,800*(i+1)))}}try{return parseJinaSpot(await getText(`https://r.jina.ai/${page}`))}catch(e){last=e;throw new Error('Spot source unavailable: '+String(last?.message||last))}}
function sourceFromTitle(title=''){return title.match(/\s+-\s+([^-]+)$/)?.[1]?.trim()||''}
function classify(title,summary){const text=`${title} ${summary}`.toLowerCase(),cats=[],dict={policy:['policy','tariff','government','regulation','permit','quota','tax','政策','关税','出口','监管','政府'],environment:['environment','water','drought','flood','protest','closure','环保','水资源','干旱','抗议','停产'],war:['war','conflict','sanction','military','geopolitical','战争','冲突','制裁','军事','地缘'],supply:['supply','mine','mining','production','inventory','expansion','shortage','供应','矿山','产量','库存','扩产','短缺'],demand:['demand','ev','battery','electric vehicle','sales','storage','需求','电动车','电池','销量','储能'],macro:['fed','rate','dollar','stock','market','inflation','美联储','利率','美元','股市','通胀']};for(const[k,w]of Object.entries(dict))if(w.some(x=>text.includes(x)))cats.push(k);return cats.length?cats:['demand']}
function sentiment(title,summary){const text=`${title} ${summary}`.toLowerCase(),pos=['shortage','cut','suspend','ban','disruption','strike','drought','delay','tight','demand growth','减产','停产','短缺','禁令','中断','罢工','干旱','需求增长'],neg=['surplus','oversupply','expansion','record output','demand slowdown','price drop','过剩','扩产','产量创新高','需求放缓','下跌'];let s=0;pos.forEach(x=>{if(text.includes(x))s++});neg.forEach(x=>{if(text.includes(x))s--});return clamp(s/3)}
async function news(){const rs=await Promise.allSettled(NEWS_FEEDS.map(async([lang,label,url])=>{const j=await getJson(`https://api.rss2json.com/v1/api.json?rss_url=${encodeURIComponent(url)}`);if(j.status!=='ok')throw new Error(j.message||'RSS failed');return(j.items||[]).map(x=>{const summary=stripHtml(x.description).slice(0,280),title=x.title||'';return{id:String(hash(x.link||title)),title,link:x.link,pubDate:x.pubDate||'',author:x.author||sourceFromTitle(title),summary,lang,source:sourceFromTitle(title)||label,categories:classify(title,summary),sentiment:sentiment(title,summary)}})}));const all=rs.flatMap(x=>x.status==='fulfilled'?x.value:[]),seen=new Set();return all.filter(x=>{const k=x.title.toLowerCase();if(!k||seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>new Date(b.pubDate)-new Date(a.pubDate)).slice(0,30)}
async function mapLimit(items,limit,worker){const out=new Array(items.length);let next=0;async function run(){while(true){const i=next++;if(i>=items.length)return;out[i]=await worker(items[i],i)}}await Promise.all(Array.from({length:Math.min(limit,items.length)},run));return out}
let existing={};try{existing=JSON.parse(await fs.readFile(outFile,'utf8'))}catch{}
const tasks=[['期货主力',()=>futures()],['现货参考',()=>spot()],['新闻',()=>news()],...MARKET_DEFS.map(d=>[`股价 ${d.name}`,()=>market(d)]),...MACRO_DEFS.map(d=>[`宏观 ${d.name}`,()=>macro(d)])];
const settled=await mapLimit(tasks,4,async([label,fn])=>{try{return{label,ok:true,value:await fn()}}catch(e){return{label,ok:false,message:String(e?.message||e)}}});
const status=[],snapshot={...existing,generatedAt:new Date().toISOString(),futures:existing.futures||null,spot:existing.spot||null,markets:Array.isArray(existing.markets)?existing.markets:[],macro:Array.isArray(existing.macro)?existing.macro:[],news:Array.isArray(existing.news)?existing.news:[],sources:SOURCES,sourceStatus:status};
settled.forEach((r,i)=>{const label=tasks[i][0];if(!r.ok){status.push({label,ok:false,message:r.message});return}status.push({label,ok:true,message:'成功'});if(label==='期货主力')snapshot.futures=r.value;else if(label==='现货参考')snapshot.spot=r.value;else if(label==='新闻')snapshot.news=r.value;else if(label.startsWith('股价 ')){const idx=snapshot.markets.findIndex(x=>x.key===r.value.key);if(idx>=0)snapshot.markets[idx]=r.value;else snapshot.markets.push(r.value)}else if(label.startsWith('宏观 ')){const idx=snapshot.macro.findIndex(x=>x.key===r.value.key);if(idx>=0)snapshot.macro[idx]=r.value;else snapshot.macro.push(r.value)}});
await fs.mkdir(path.dirname(outFile),{recursive:true});await fs.writeFile(outFile,JSON.stringify(snapshot,null,2)+'\n','utf8');console.log(`Wrote ${outFile}: ${status.filter(x=>x.ok).length}/${status.length} sources succeeded; preserved snapshot for failures`);if(!snapshot.futures)process.exitCode=2;
